import java.util.ArrayList;
import java.util.Scanner;
import java.io.File;
import java.io.IOException;
import java.util.Random;
public class Player
{
  public ArrayList<Card> creatures;
  public ArrayList<Card> lands;

  public ArrayList<Card> library;
  public ArrayList<Card> hand;
  public ArrayList<Card> graveyard;
  public ArrayList<Card> exile;
  
  public int[] manaPool;

  public int life;
  public int poison; //Because why not?

  public int landsToPlay;
  public int landsPerTurn = 1;

  public String name = "";

  public Player()
  {
    creatures = new ArrayList<Card>();
    lands = new ArrayList<Card>();
    library = new ArrayList<Card>();
    hand = new ArrayList<Card>();
    graveyard = new ArrayList<Card>();
    exile = new ArrayList<Card>();
    life = 20;

    landsToPlay = 1;

    manaPool = new int[Card.COLORS];
  }

  public Player(String nname)
  {
    this();
    name = nname;
  }

  public Player(Player pl)
  {
    this(pl.name);
    life = pl.life;
    for(Card p:pl.creatures)
      creatures.add(new Card(p));
    for(Card p:pl.lands)
      lands.add(new Card(p));
    for(Card c:pl.library)
      library.add(new Card(c));
    for(Card c:pl.hand)
      hand.add(new Card(c));
    for(Card c:pl.graveyard)
      graveyard.add(new Card(c));
    for(Card c:pl.exile)
      exile.add(new Card(c));
  }

  public void untap()
  {
    for(Card p:creatures)
      p.untap();
    for(Card p:lands)
      p.untap();
    landsToPlay = landsPerTurn;
  }

  public boolean playLand(Card c)
  {
    if(hand.remove(c))
    {
      lands.add(c);
      landsToPlay--;
      return true;
    }
    return false;
  }

  public boolean playCard(Card c)
  {
    if(c.isCreature())
    {
      if(hand.remove(c))
      {
        creatures.add(c);
        return true;
      }
    }
    else
    {
      if(hand.remove(c))
      {
        return true;
      }
    }
    return false;
  }

  //Deck stuff (maybe move to Library if we make a class like that)
  public void loadDeck(String fname)
  {
    library = new ArrayList<Card>(60);
    try
    {
      Scanner deckReader = new Scanner(new File(fname));
      int num;
      String line;
      while(deckReader.hasNextLine())
      {
        num = deckReader.nextInt();
        line = deckReader.nextLine();
        line = line.trim(); // Remove leading space
        for(int i=0;i<num;i++)
          library.add(new Card(line));
      }
      deckReader.close();
    }
    catch(IOException e)
    {System.out.println("Error reading deck.");}
  }

    /* Randomization algorithm from Tic Tac Oh No random generator.
   * Apparently this is something called "Fisher-Yates" or Knuths "Algorithm P",
   * but those references were not used.
   * Note that this technically might not cover all permutations, depending on how
   * the random numbers are generated by Random (number of possible seeds might be too
   * small).
   *
   * In the future, maybe implement various simulated shuffle techniques (riffle,
   * bridge, pile ("Magic shuffle"), clump, etc.).*/
  public void shuffleDeck()
  {
    Random rand = new Random();
    int open = library.size();
    int k;
    Card temp;
    while(open>0)
    {
      k = rand.nextInt(open);
      open--;
      if(k!=open)
      {
        temp = library.get(k);
        library.set(k, library.get(open));
        library.set(open, temp);
      }
    }
  }

  public void drawCard()
  {
    hand.add(library.remove(library.size()-1));
  }

  public void drawCards(int num)
  {
    for(int i=0;i<num;i++)
      drawCard();
  }

  public ArrayList<Card> determineAvailableMoves()
  {
    int[] mana = new int[Card.COLORS];

    // Start by considering mana currently left in pool.
    for(int i = 0; i<Card.COLORS;i++)
      mana[i] = manaPool[i];

    /* See what mana we can get from untapped lands
     * For now, we just have lands as tapping for their "cost"*/
    for(Card l:lands)
      for(int i=0;i<Card.COLORS;i++)
        if(!l.tapped)
          mana[i]+=l.cost[i];

    int totalMana = 0;
    for(int i = 0; i<Card.COLORS; i++)
      totalMana+=mana[i];

    ArrayList<Card> moveList = new ArrayList<Card>();
    for(Card c:hand)
    {
      boolean canPlay = true;
      if(c.isLand())
      {
        canPlay = (landsToPlay > 0);
      }
      else
      {
        int totalCost = c.cost[Card.COLORS-1];
        for(int i = Card.COLORS-2;i>=0;i--)
        {
          if (mana[i] < c.cost[i])
          {
            canPlay = false;
            break;
          }
          totalCost+=c.cost[i];
        }
        if (totalCost > totalMana)
          canPlay = false;
      }
      if(canPlay)
        moveList.add(c);
    }
    return moveList;
  }

  public void printBoard()
  {
    System.out.print(name + "'s hand: |");
    for(Card c:hand)
      System.out.print(c.name + "|");
    System.out.println();

    System.out.print(name + "'s creatures: |");
    for(Card c:creatures)
      System.out.print(c.name + ", " + c.power + "/" + c.toughness + 
                       (c.tapped ? "(T)" : "") + "|");
    System.out.println();

    System.out.print(name + "'s lands: |");
    for(Card c:lands)
      System.out.print(c.name + (c.tapped ? "(T)" : "") + "|");
    System.out.println();

    //System.out.print(name + "'s mana pool: ");
  }

}